FROM centos:8

RUN yum update -y && \
    yum install -y wget unzip maven java-11-openjdk-devel npm && \
    npm install -g @angular/cli

RUN wget https://services.gradle.org/distributions/gradle-6.3-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-*.zip

ENV GRADLE_BIN /opt/gradle/gradle-6.3/bin
ENV PATH $PATH:${GRADLE_BIN}

RUN yum -y clean all
